FROM microsoft/dotnet:latest

# Create directory from the app source code
RUN MKDIR -p /app
WORKDIR /app

# Copy source code and restore dependencies
COPY . /app
RUN dotnet restore

# Expose the port and start app
EXPOSE 36098
CMD [ "dotnet", "run" ]